name: Deploy to Remote Server

on:
  push:
    branches:
      - main # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: 5|Z<6^l%1£:16&^q_!Gzn-47

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i 5|Z<6^l%1£:16&^q_!Gzn-47 root@134.209.145.61'
            cd /var/www/html/hishabee/lara-docker &&
            git pull origin main &&
            docker-compose down &&
            docker-compose build &&
            docker-compose up -d
          '
        env:
          SSH_PRIVATE_KEY: 5|Z<6^l%1£:16&^q_!Gzn-47
