name: Deploy to DigitalOcean

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Main Server
        uses: appleboy/ssh-action@master
        with:
          host: "134.209.145.61"
          username: "root"
          password: "5|Z<6^l%1£:16&^q_!Gzn-47"
          script: |
            cd  /var/www/html/hishabee/lara-docker/ &&
            git pull origin main &&
            docker compose down &&
            docker compose build &&
            docker compose up -d
